export type ProductResource = { label: string; url: string };

export type AffiliateProduct = {
  id: number;
  merchant: "DHgate" | "Philips" | "RevoMatic";
  title: string;
  category: string;
  description: string;
  features: string[];
  affiliateUrl: string;
  badge: string;
  note?: string;
  imageUrl?: string;
  resources?: ProductResource[];
};

export const affiliateProducts: AffiliateProduct[] = [
  { id: 1, merchant: "DHgate", title: "Portable Digital Voice Recorder", category: "Audio & Productivity", description: "A wallet-size rechargeable recorder for lectures, meetings, interviews, and quick audio notes, with voice activation, timestamping, and expandable storage.", features: ["Approx. 40-hour recording time", "Voice activation", "WAV + USB 2.0", "Up to 128 GB card support"], affiliateUrl: "https://dhgate.sjv.io/k4NeKd", badge: "Compact recorder" },
  { id: 2, merchant: "DHgate", title: "TEYUN A4 4-Channel Audio Mixer", category: "Creator Tech", description: "A compact mixer for livestreaming, podcasting, karaoke, and home recording with Bluetooth playback, USB connectivity, and 48V phantom power.", features: ["4-channel mixing", "48V phantom power", "Bluetooth playback", "USB/PC recording"], affiliateUrl: "https://dhgate.sjv.io/oNB1Km", badge: "Creator gear", imageUrl: "https://i5.walmartimages.com/asr/368e7579-8f7c-4d0a-a252-efc1839fcc72.5fd560202a5555de64d67e949176e861.jpeg?odnBg=FFFFFF&odnHeight=612&odnWidth=612" },
  { id: 3, merchant: "DHgate", title: "OTG Micro SD / USB 2.0 Card Reader", category: "Computer Accessories", description: "A compact OTG card reader for moving photos, videos, and files between memory cards and compatible computers, phones, or tablets.", features: ["USB 2.0", "OTG support", "SD / microSD access", "Portable file transfer"], affiliateUrl: "https://dhgate.sjv.io/E0WmNK", badge: "Everyday tech" },
  { id: 4, merchant: "DHgate", title: "M9 Instant Voice Translator", category: "Travel Tech", description: "A pocket touchscreen translator for travel and face-to-face conversations with online translation, offline language support, and camera/text translation features.", features: ["3-inch IPS display", "Wi-Fi + Bluetooth", "Offline language support", "Photo/text translation"], affiliateUrl: "https://dhgate.sjv.io/MKWJLo", badge: "Travel pick", imageUrl: "https://imgaz1.staticbg.com/thumb/large/oaupload/ser1/banggood/images/BB/A9/dca7376c-0696-47cb-ba22-91b7ca0be24a.png.webp" },
  { id: 6, merchant: "Philips", title: "Philips 7000 Series 2K Dual-Cam Video Doorbell", category: "Smart Home Security", description: "A rechargeable dual-camera doorbell designed to show both visitors and the doorstep/package area with high-resolution video and app alerts.", features: ["2K HDR video", "Dual-camera coverage", "Motion alerts", "10,000mAh rechargeable battery"], affiliateUrl: "https://philipsamazonseller.sjv.io/vDOBMv", badge: "Home security", note: "DDA270X-2TXS", imageUrl: "https://media.binglee.com.au/8/8/7/5/8875ee256cea55b0d3a35fea90d9f1c31f88a67a_Philips_DDA270X_2TXS3_VideoDoorbell_Hero_4.jpg", resources: [{ label: "Watch product video", url: "https://www.youtube.com/watch?v=V5I9iOZwPqQ" }, { label: "Read setup manual", url: "https://manuals.plus/asin/B0DK6RYLSM" }] },
  { id: 7, merchant: "Philips", title: "Philips 7000 Series Video Doorbell + Wi-Fi Chime", category: "Smart Home Security", description: "A Philips 7000 Series dual-camera doorbell package paired with a Wi-Fi chime for front-door visitor and package monitoring.", features: ["2K dual-camera video", "HDR", "Wi-Fi chime", "Smartphone alerts"], affiliateUrl: "https://philipsamazonseller.sjv.io/4aqb9n", badge: "Doorbell bundle", note: "DDA270X-2TXS bundle", imageUrl: "https://media.binglee.com.au/8/8/7/5/8875ee256cea55b0d3a35fea90d9f1c31f88a67a_Philips_DDA270X_2TXS3_VideoDoorbell_Hero_4.jpg", resources: [{ label: "Watch product video", url: "https://www.youtube.com/watch?v=V5I9iOZwPqQ" }, { label: "Read setup manual", url: "https://manuals.plus/asin/B0DK6RYLSM" }] },
  { id: 8, merchant: "Philips", title: "Philips 5000 Series Palm Recognition Smart Lock", category: "Smart Locks", description: "A Wi-Fi smart deadbolt with palm-vein recognition plus PIN, mechanical key, and app-based access for convenient keyless entry.", features: ["Palm recognition", "Built-in Wi-Fi", "PIN + key backup", "Remote app access"], affiliateUrl: "https://philipsamazonseller.sjv.io/yZB0M3", badge: "Keyless entry", note: "DDL250X-14HWC", imageUrl: "https://media.binglee.com.au/9/8/c/c/98ccd45de0f466447c80dc3a2659202764c41235_Philips_DDL250X_14HWC_Smart_Digital_Door_Locks_Hero_1.jpg", resources: [{ label: "Installation video", url: "https://www.youtube.com/watch?v=vPlFv0gz9dE" }, { label: "Philips support", url: "https://us.homeaccess.philips/pages/support" }] },
  { id: 9, merchant: "Philips", title: "Philips 5000 Series Palm Recognition Wi-Fi Lock Bundle", category: "Smart Locks", description: "A bundle built around the Philips 5000 Series palm-recognition smart lock with mounting hardware, batteries, and a wireless chime.", features: ["Palm recognition", "Wi-Fi control", "Wireless chime", "Mounting hardware included"], affiliateUrl: "https://philipsamazonseller.sjv.io/7XQ2Pg", badge: "Smart lock bundle", note: "DDL250X-14HWC bundle", imageUrl: "https://media.binglee.com.au/9/8/c/c/98ccd45de0f466447c80dc3a2659202764c41235_Philips_DDL250X_14HWC_Smart_Digital_Door_Locks_Hero_1.jpg", resources: [{ label: "Installation video", url: "https://www.youtube.com/watch?v=vPlFv0gz9dE" }, { label: "Philips support", url: "https://us.homeaccess.philips/pages/support" }] },
  { id: 10, merchant: "Philips", title: "Philips 3000 Series Wi-Fi Retrofit Lock with Fingerprint Keypad", category: "Smart Locks", description: "A retrofit smart-lock system that upgrades an existing deadbolt while preserving the exterior key and adding fingerprint, PIN, app control, voice-assistant support, and automatic locking.", features: ["Fingerprint + PIN keypad", "Built-in 2.4 GHz Wi-Fi", "Alexa + Google Assistant support", "Remote app control + auto-lock"], affiliateUrl: "https://philipsamazonseller.sjv.io/qWBJMY", badge: "Retrofit upgrade", note: "DDL230X-1HWP", resources: [{ label: "Official product guide", url: "https://us.homeaccess.philips/products/philips-3000-series-wi-fi-retrofit-lock-with-keypad" }, { label: "How to install / program", url: "https://us.homeaccess.philips/products/philips-3000-series-wi-fi-retrofit-lock-with-keypad" }, { label: "Philips support", url: "https://us.homeaccess.philips/pages/support" }] },
  { id: 11, merchant: "RevoMatic", title: "REVO Therapy Massage Oil", category: "Massage & Body Care", description: "A massage oil designed to add glide and moisture during body-massage, cupping, and sculpting-style routines.", features: ["Massage glide", "Body-care use", "Pairs with REVO devices", "Moisturizing routine"], affiliateUrl: "https://revomadicamazon.pxf.io/AgG9vR", badge: "Body care" },
  { id: 12, merchant: "RevoMatic", title: "REVO Smart Cupping Therapy Massager", category: "Recovery & Massage", description: "An electric cupping massager combining adjustable suction, warmth, and red-light illumination for an at-home massage and recovery routine.", features: ["12 customizable settings", "Therapeutic heat", "660nm red-light illumination", "Dynamic suction"], affiliateUrl: "https://revomadicamazon.pxf.io/1GV0vg", badge: "Recovery pick", imageUrl: "https://revomadic.com/cdn/shop/files/REVO-Smart-Cup_b3899134-0d74-4ebb-9c6f-6b88a9f84ed0.jpg?v=1741395863&width=2048", resources: [{ label: "Official video tutorials", url: "https://revomadic.com/de/pages/revo-video-guide" }, { label: "Watch REVO video", url: "https://www.youtube.com/watch?v=Oo8Nc4qzDYc" }] },
  { id: 13, merchant: "RevoMatic", title: "REVO Face Genie LED Facial Device", category: "Beauty Tech", description: "A compact facial-care device combining LED modes, gentle stimulation, warmth, and vibration for an at-home skincare routine.", features: ["Multi-color LED modes", "Heat + vibration", "Portable design", "Facial massage"], affiliateUrl: "https://revomadicamazon.pxf.io/ZVROMR", badge: "Beauty tech" },
  { id: 14, merchant: "RevoMatic", title: "REVO Arnica Joint & Muscle Cream", category: "Topical Body Care", description: "A cooling arnica-based topical cream positioned as a post-massage and body-care companion for muscles and joints.", features: ["Arnica-based topical", "Cooling body care", "Post-massage use", "Compact tube"], affiliateUrl: "https://revomadicamazon.pxf.io/gR4jx5", badge: "Recovery care" },
  { id: 15, merchant: "RevoMatic", title: "REVO Sculptor Body Sculpting Massager", category: "Massage Tech", description: "A handheld body-massage device combining vacuum suction, warmth, and red light for use on areas such as the arms, thighs, waist, and legs.", features: ["Vacuum suction", "Heat", "Red light", "Multiple treatment areas"], affiliateUrl: "https://revomadicamazon.pxf.io/0G1Wv3", badge: "Body massage" },
  { id: 16, merchant: "RevoMatic", title: "REVO Collagen Jelly", category: "Skincare", description: "A jelly-texture facial moisturizer designed to add hydration and slip to a skincare routine, including use alongside facial-care devices.", features: ["Jelly moisturizer", "Face + neck use", "Hydrating routine", "Pairs with Face Genie"], affiliateUrl: "https://revomadicamazon.pxf.io/B51rv9", badge: "Skincare" },
  { id: 17, merchant: "RevoMatic", title: "REVO Wave Vibration Platform", category: "Fitness & Recovery", description: "A vibration platform for low-impact home movement and fitness routines with a remote control, resistance bands, and multiple intensity settings.", features: ["180 intensity levels", "5 automatic modes", "Resistance bands", "660nm red-light array"], affiliateUrl: "https://revomadicamazon.pxf.io/oNB1kg", badge: "Home fitness", imageUrl: "https://pisces.bbystatic.com/prescaled/500/500/image2/BestBuy_US/images/products/31a94e29-0bbc-4504-bf27-a45bedef1655.jpg", resources: [{ label: "Official product & use guide", url: "https://revomadic.com/products/revo-wave" }, { label: "User manual", url: "https://manuals.plus/revomadic/b0ghqlcnqr-wave-board-with-red-light-therapy-manual" }] },
  { id: 18, merchant: "RevoMatic", title: "The Pill by REVO Mini Massage Gun", category: "Percussion Massage", description: "A compact rechargeable percussion massager with multiple speed levels and interchangeable heads for portable post-workout or everyday muscle massage.", features: ["Compact massage gun", "Multiple speeds", "4 attachments", "Rechargeable"], affiliateUrl: "https://revomadicamazon.pxf.io/k4NerM", badge: "Portable recovery", imageUrl: "https://revomadic.com/cdn/shop/files/what_sincluded2.1square.jpg?v=1694796799", resources: [{ label: "Official product guide", url: "https://www.revomadic.com/de/products/the-pill-by-revo-mini-massage-gun" }] },
  { id: 19, merchant: "RevoMatic", title: "REVO Face Genie x Collagen Jelly Cream — Face & Neck Starter Kit", category: "Beauty Tech Bundle", description: "A two-piece face-and-neck starter kit pairing the REVO Face Genie facial device with REVO Collagen Jelly for a combined skincare and device routine.", features: ["Face Genie facial device", "Collagen Jelly included", "2-piece face + neck starter kit", "LED / heat / vibration skincare routine"], affiliateUrl: "https://revomadicamazon.pxf.io/enb9Lg", badge: "Starter kit", note: "Face Genie + Collagen Jelly bundle" },
];

export const merchantOrder = ["DHgate", "Philips", "RevoMatic"] as const;
