import { affiliateProducts } from "../../app/affiliate-services/products";

export type UnifiedAffiliateItem = {
  id: string;
  merchant: string;
  title: string;
  category: string;
  description: string;
  features: string[];
  affiliateUrl: string;
  source: "central-catalog" | "brand-page";
  pagePath?: string;
};

const centralCatalog: UnifiedAffiliateItem[] = affiliateProducts.map((product) => ({
  id: `central-${product.id}`,
  merchant: product.merchant,
  title: product.title,
  category: product.category,
  description: product.description,
  features: product.features,
  affiliateUrl: product.affiliateUrl,
  source: "central-catalog",
}));

const brandPageCatalog: UnifiedAffiliateItem[] = [
  {
    id: "eurooptic-garmin-quatix-8-pro",
    merchant: "EuroOptic",
    title: "Garmin Quatix 8 Pro",
    category: "Smartwatches & Outdoor Tech",
    description: "Featured Garmin smartwatch offered through the WASCIK EuroOptic partner page, with current price, availability, specifications, shipping, and returns confirmed at the merchant listing.",
    features: ["Garmin smartwatch", "Outdoor and specialty gear", "Featured EuroOptic product"],
    affiliateUrl: "https://eurooptic.sjv.io/WOEqjX",
    source: "brand-page",
    pagePath: "/affiliate-services/eurooptic",
  },
  {
    id: "eurooptic-store",
    merchant: "EuroOptic",
    title: "EuroOptic Specialty Gear Store",
    category: "Optics, Outdoor Gear & Watches",
    description: "Browse EuroOptic's current optics, outdoor equipment, watches, and specialty gear catalog through WASCIK's tracked store link.",
    features: ["Optics", "Outdoor equipment", "Watches", "Specialty gear"],
    affiliateUrl: "https://eurooptic.sjv.io/c/7587435/2973190/35464",
    source: "brand-page",
    pagePath: "/affiliate-services/eurooptic",
  },
  {
    id: "focus-garmin-dezlcam-otr725",
    merchant: "Focus Camera",
    title: "Garmin dezlCam OTR725",
    category: "GPS Navigation & Dash Cameras",
    description: "A seven-inch GPS truck navigator with a built-in dash camera for professional drivers and life on the road.",
    features: ["7-inch touchscreen", "Built-in dash camera", "Truck navigation"],
    affiliateUrl: "https://focuscamera.pxi6.net/3kzXRX",
    source: "brand-page",
    pagePath: "/affiliate-services/focus-camera",
  },
  {
    id: "focus-camera-store",
    merchant: "Focus Camera",
    title: "Focus Camera Main Store",
    category: "Cameras, Navigation, Electronics & Lifestyle",
    description: "Browse current camera, navigation, electronics, and lifestyle products through WASCIK's tracked Focus Camera store link.",
    features: ["Cameras", "Navigation", "Electronics", "Lifestyle products"],
    affiliateUrl: "https://focuscamera.pxi6.net/c/7587435/642856/10228",
    source: "brand-page",
    pagePath: "/affiliate-services/focus-camera",
  },
  {
    id: "aquacurve-store",
    merchant: "AquaCurve",
    title: "AquaCurve Poolside & Outdoor Living Catalog",
    category: "Poolside Furniture & Outdoor Living",
    description: "Browse AquaCurve's current poolside and outdoor-living catalog through the WASCIK affiliate store link.",
    features: ["Poolside furniture", "Outdoor living", "Patio and leisure products"],
    affiliateUrl: "https://aquacurve.sjv.io/c/7587435/3859681/51362?trafsrc=impact",
    source: "brand-page",
    pagePath: "/affiliate-services/aquacurve",
  },
  {
    id: "gearup-mobile",
    merchant: "GearUP",
    title: "GearUP for Mobile",
    category: "Gaming Network Optimization",
    description: "A mobile game connection-optimization service for Android and iOS players dealing with unstable latency, lag spikes, or high ping.",
    features: ["Android and iOS", "One-tap boosting", "Worldwide game servers", "Connection optimization"],
    affiliateUrl: "https://gearupapp.pxf.io/c/7587435/3911079/53368",
    source: "brand-page",
    pagePath: "/affiliate-services/gearup",
  },
  {
    id: "arccaptain-store",
    merchant: "ArcCaptain",
    title: "ArcCaptain Welding Equipment",
    category: "Welding Equipment & Accessories",
    description: "Browse ArcCaptain MIG, TIG, stick, and plasma equipment, along with welding helmets and accessories through WASCIK's approved affiliate link.",
    features: ["MIG welding", "TIG welding", "Stick and plasma equipment", "Welding helmets and accessories"],
    affiliateUrl: "https://arccaptain.pxf.io/c/7587435/3898395/52929",
    source: "brand-page",
    pagePath: "/affiliate-services#arccaptain",
  },
  {
    id: "ticketnetwork-store",
    merchant: "TicketNetwork",
    title: "TicketNetwork Concerts & Event Tickets",
    category: "Concerts, Events & Tickets",
    description: "Search current TicketNetwork listings for concerts and events through WASCIK's ticket affiliate page.",
    features: ["Concert tickets", "Live events", "Current seat listings", "Ticket resale marketplace"],
    affiliateUrl: "https://goto.ticketnetwork.com/c/7587435/120057/2322",
    source: "brand-page",
    pagePath: "/affiliate-services/ticketnetwork",
  },
  {
    id: "ticketnetwork-chris-stapleton",
    merchant: "TicketNetwork",
    title: "Chris Stapleton — All-American Road Show",
    category: "Country Concert",
    description: "Chris Stapleton with Zach Top and Allen Stone, Friday, August 14, 2026 at 7:30 PM, Fenway Park in Boston, Massachusetts.",
    features: ["Featured on WASCIK TicketNetwork page", "Concert ticket search", "Country Concert"],
    affiliateUrl: "https://goto.ticketnetwork.com/c/7587435/120057/2322",
    source: "brand-page",
    pagePath: "/affiliate-services/ticketnetwork",
  },
  {
    id: "ticketnetwork-kane-brown",
    merchant: "TicketNetwork",
    title: "Kane Brown — OC Smoke Show",
    category: "Country Concert",
    description: "Kane Brown with Dustin Lynch and LoCash, Saturday, August 15, 2026 at 1:00 PM, Rancho Mission Viejo Riding Park in San Juan Capistrano, California.",
    features: ["Featured on WASCIK TicketNetwork page", "Concert ticket search", "Country Concert"],
    affiliateUrl: "https://goto.ticketnetwork.com/c/7587435/120057/2322",
    source: "brand-page",
    pagePath: "/affiliate-services/ticketnetwork",
  },
  {
    id: "ticketnetwork-guns-n-roses",
    merchant: "TicketNetwork",
    title: "Guns N’ Roses with Public Enemy",
    category: "Rock Concert",
    description: "Guns N’ Roses with Public Enemy, Sunday, August 16, 2026 at 6:25 PM, Busch Stadium in St. Louis, Missouri.",
    features: ["Featured on WASCIK TicketNetwork page", "Concert ticket search", "Rock Concert"],
    affiliateUrl: "https://goto.ticketnetwork.com/c/7587435/120057/2322",
    source: "brand-page",
    pagePath: "/affiliate-services/ticketnetwork",
  },
  {
    id: "ticketnetwork-pitbull",
    merchant: "TicketNetwork",
    title: "Pitbull with Lil Jon",
    category: "Pop & Hip-Hop Concert",
    description: "Pitbull with Lil Jon, Wednesday, August 19, 2026 at 8:00 PM, Jiffy Lube Live in Bristow, Virginia.",
    features: ["Featured on WASCIK TicketNetwork page", "Concert ticket search", "Pop & Hip-Hop Concert"],
    affiliateUrl: "https://goto.ticketnetwork.com/c/7587435/120057/2322",
    source: "brand-page",
    pagePath: "/affiliate-services/ticketnetwork",
  },
  {
    id: "ticketnetwork-garth-brooks-aug-20",
    merchant: "TicketNetwork",
    title: "Garth Brooks Live — August 20",
    category: "Country Concert",
    description: "Garth Brooks live, Thursday, August 20, 2026 at 7:30 PM, Gainbridge Fieldhouse in Indianapolis, Indiana.",
    features: ["Featured on WASCIK TicketNetwork page", "Concert ticket search", "Country Concert"],
    affiliateUrl: "https://goto.ticketnetwork.com/c/7587435/120057/2322",
    source: "brand-page",
    pagePath: "/affiliate-services/ticketnetwork",
  },
  {
    id: "ticketnetwork-garth-brooks-aug-21",
    merchant: "TicketNetwork",
    title: "Garth Brooks Live — August 21",
    category: "Country Concert",
    description: "Garth Brooks live, Friday, August 21, 2026 at 8:00 PM, Gainbridge Fieldhouse in Indianapolis, Indiana.",
    features: ["Featured on WASCIK TicketNetwork page", "Concert ticket search", "Country Concert"],
    affiliateUrl: "https://goto.ticketnetwork.com/c/7587435/120057/2322",
    source: "brand-page",
    pagePath: "/affiliate-services/ticketnetwork",
  },
  {
    id: "ticketnetwork-garth-brooks-aug-22",
    merchant: "TicketNetwork",
    title: "Garth Brooks Live — August 22",
    category: "Country Concert",
    description: "Garth Brooks live, Saturday, August 22, 2026 at 8:00 PM, Gainbridge Fieldhouse in Indianapolis, Indiana.",
    features: ["Featured on WASCIK TicketNetwork page", "Concert ticket search", "Country Concert"],
    affiliateUrl: "https://goto.ticketnetwork.com/c/7587435/120057/2322",
    source: "brand-page",
    pagePath: "/affiliate-services/ticketnetwork",
  },
  {
    id: "ticketnetwork-garth-brooks-aug-23",
    merchant: "TicketNetwork",
    title: "Garth Brooks Live — August 23",
    category: "Country Concert",
    description: "Garth Brooks live, Sunday, August 23, 2026 at 2:00 PM, Gainbridge Fieldhouse in Indianapolis, Indiana.",
    features: ["Featured on WASCIK TicketNetwork page", "Concert ticket search", "Country Concert"],
    affiliateUrl: "https://goto.ticketnetwork.com/c/7587435/120057/2322",
    source: "brand-page",
    pagePath: "/affiliate-services/ticketnetwork",
  },
  {
    id: "ticketnetwork-weezer",
    merchant: "TicketNetwork",
    title: "Weezer with The Shins & Silversun Pickups",
    category: "Alternative Rock Concert",
    description: "Weezer with The Shins and Silversun Pickups, Tuesday, October 6, 2026 at 7:00 PM, Nationwide Arena in Columbus, Ohio.",
    features: ["Featured on WASCIK TicketNetwork page", "Concert ticket search", "Alternative Rock Concert"],
    affiliateUrl: "https://goto.ticketnetwork.com/c/7587435/120057/2322",
    source: "brand-page",
    pagePath: "/affiliate-services/ticketnetwork",
  },
  {
    id: "ticketnetwork-journey",
    merchant: "TicketNetwork",
    title: "Journey Live in Concert",
    category: "Classic Rock Concert",
    description: "Journey live, Thursday, October 8, 2026 at 7:30 PM, BOK Center in Tulsa, Oklahoma.",
    features: ["Featured on WASCIK TicketNetwork page", "Concert ticket search", "Classic Rock Concert"],
    affiliateUrl: "https://goto.ticketnetwork.com/c/7587435/120057/2322",
    source: "brand-page",
    pagePath: "/affiliate-services/ticketnetwork",
  },
  {
    id: "eurooptic-garmin-inreach-mini-2-gps-satellite-communicator",
    merchant: "EuroOptic",
    title: "Garmin inReach Mini 2 GPS Satellite Communicator",
    category: "Satellite communication & navigation",
    description: "A compact black GPS satellite communicator designed for off-grid trips, route awareness, and staying connected beyond normal cellular coverage.",
    features: ["Compact handheld design","GPS navigation support","Satellite communication capabilities"],
    affiliateUrl: "https://eurooptic.sjv.io/JkZoPe",
    source: "brand-page",
    pagePath: "/affiliate-services/eurooptic",
  },
  {
    id: "eurooptic-fujinon-polaris-7x50-fmtr-sx2-waterproof-binoculars",
    merchant: "EuroOptic",
    title: "Fujinon Polaris 7x50 FMTR-SX2 Waterproof Binoculars",
    category: "Optics & outdoor observation",
    description: "Rugged waterproof binoculars built for detailed outdoor and marine observation with multicoated optics, a rubberized body, and field-flattener lenses.",
    features: ["Waterproof construction","Multicoated optical system","Rubberized body and field-flattener lenses"],
    affiliateUrl: "https://eurooptic.sjv.io/4aMR9L",
    source: "brand-page",
    pagePath: "/affiliate-services/eurooptic",
  },
  {
    id: "eurooptic-leofoto-pc-20-blue-mobile-phone-stand",
    merchant: "EuroOptic",
    title: "Leofoto PC-20 Blue Mobile Phone Stand",
    category: "Mobile photography accessory",
    description: "A compact blue mobile-phone stand designed for convenient tabletop positioning and easy attachment to compatible photography support equipment.",
    features: ["Compact folding design","Blue metal construction"],
    affiliateUrl: "https://eurooptic.sjv.io/Ag5k7K",
    source: "brand-page",
    pagePath: "/affiliate-services/eurooptic",
  },
  {
    id: "eurooptic-garmin-instinct-3-45mm-solar-tactical-edition-smartwatch",
    merchant: "EuroOptic",
    title: "Garmin Instinct 3 45mm Solar Tactical Edition Smartwatch",
    category: "Outdoor technology & tactical wearables",
    description: "A rugged black 45mm GPS smartwatch with solar charging support and tactical-focused features for outdoor training, navigation, and everyday activity tracking.",
    features: ["Solar charging support","Rugged 45mm GPS watch design","Tactical-edition activity and navigation features"],
    affiliateUrl: "https://eurooptic.sjv.io/3kzXgr",
    source: "brand-page",
    pagePath: "/affiliate-services/eurooptic",
  },
  {
    id: "eurooptic-oakley-meta-vanguard-white-prizm-black-shield-sunglasses",
    merchant: "EuroOptic",
    title: "Oakley Meta Vanguard White Prizm Black Shield Sunglasses",
    category: "Smart eyewear & performance sunglasses",
    description: "Performance-focused Oakley Meta smart eyewear in white with a Prizm Black shield lens and a streamlined semi-rimless wraparound design.",
    features: ["Oakley Meta smart-eyewear platform","Prizm Black shield lens","Lightweight semi-rimless performance frame"],
    affiliateUrl: "https://eurooptic.sjv.io/vDm1A3",
    source: "brand-page",
    pagePath: "/affiliate-services/eurooptic",
  },
  {
    id: "eurooptic-ray-ban-meta-skyler-shiny-chalky-gray-transitions-sapphire-s",
    merchant: "EuroOptic",
    title: "Ray-Ban Meta Skyler Shiny Chalky Gray Transitions Sapphire Sunglasses",
    category: "Smart eyewear & transition lenses",
    description: "Ray-Ban Meta Skyler smart glasses in a shiny chalky-gray frame with Transitions Sapphire lenses that adapt as lighting conditions change.",
    features: ["Ray-Ban Meta smart-eyewear platform","Transitions Sapphire lenses","Rounded Skyler frame in shiny chalky gray"],
    affiliateUrl: "https://eurooptic.sjv.io/oNJP1W",
    source: "brand-page",
    pagePath: "/affiliate-services/eurooptic",
  },
  {
    id: "eurooptic-oakley-holbrook-matte-black-prizm-dark-golf-sunglasses",
    merchant: "EuroOptic",
    title: "Oakley Holbrook Matte Black PRIZM Dark Golf Sunglasses",
    category: "Performance eyewear & golf lenses",
    description: "Oakley Holbrook sunglasses with a matte-black frame and PRIZM Dark Golf lenses designed to enhance contrast and visual detail on the course.",
    features: ["PRIZM Dark Golf lenses","Classic Holbrook frame","Matte-black finish"],
    affiliateUrl: "https://eurooptic.sjv.io/B5kerJ",
    source: "brand-page",
    pagePath: "/affiliate-services/eurooptic",
  },
  {
    id: "eurooptic-oakley-edge-icon-shoes-in-white",
    merchant: "EuroOptic",
    title: "Oakley Edge Icon Shoes in White",
    category: "Performance footwear",
    description: "Oakley Edge Icon slip-on performance shoes in a clean white colorway, combining a streamlined upper with a sculpted, high-traction outsole.",
    features: ["Slip-on athletic design","Sculpted cushioned sole","White monochrome colorway"],
    affiliateUrl: "https://eurooptic.sjv.io/PznY3R",
    source: "brand-page",
    pagePath: "/affiliate-services/eurooptic",
  },
  {
    id: "eurooptic-oakley-edge-icon-shoes-in-mist-and-pebble",
    merchant: "EuroOptic",
    title: "Oakley Edge Icon Shoes in Mist and Pebble",
    category: "Performance footwear",
    description: "Oakley Edge Icon slip-on performance shoes in a Mist and Pebble colorway with navy accents and a rugged, sculpted outsole.",
    features: ["Slip-on athletic design","Cushioned high-traction outsole","Mist, Pebble, and navy color palette"],
    affiliateUrl: "https://eurooptic.sjv.io/enjJVX",
    source: "brand-page",
    pagePath: "/affiliate-services/eurooptic",
  },
  {
    id: "eurooptic-oakley-edge-icon-shoes-in-blackout",
    merchant: "EuroOptic",
    title: "Oakley Edge Icon Shoes in Blackout",
    category: "Performance footwear",
    description: "Oakley Edge Icon slip-on performance shoes in an all-black Blackout finish with a sculpted sole and tonal Oakley detailing.",
    features: ["Slip-on athletic design","Sculpted cushioned sole","All-black tonal finish"],
    affiliateUrl: "https://eurooptic.sjv.io/B5keZW",
    source: "brand-page",
    pagePath: "/affiliate-services/eurooptic",
  },
  {
    id: "focus-poseidon-nano-3000mah-wireless-charger",
    merchant: "Focus Camera",
    title: "Poseidon Nano 3000mAh Wireless Charger",
    category: "Portable power",
    description: "A compact 3000mAh wireless charging solution built for convenient backup power without adding a bulky full-size battery pack to your everyday carry.",
    features: ["Compact portable design","3000mAh power capacity","Built-in Mavrik charging technology"],
    affiliateUrl: "https://focuscamera.pxi6.net/Ag5kVR",
    source: "brand-page",
    pagePath: "/affiliate-services/focus-camera",
  },
  {
    id: "focus-emeet-c980-pro-full-hd-webcam",
    merchant: "Focus Camera",
    title: "eMeet C980 Pro Full HD Webcam",
    category: "Work & video calls",
    description: "An all-in-one Full HD webcam designed to simplify meetings, remote work, classes, and everyday video calls with integrated audio hardware.",
    features: ["Full HD video","Noise-reduction microphone","Built-in speakers"],
    affiliateUrl: "https://focuscamera.pxi6.net/aNDYVj",
    source: "brand-page",
    pagePath: "/affiliate-services/focus-camera",
  },
  {
    id: "focus-zoom-zdm-1-four-person-podcast-bundle",
    merchant: "Focus Camera",
    title: "Zoom ZDM-1 Four-Person Podcast Bundle",
    category: "Podcast & creator gear",
    description: "A coordinated four-person podcast setup that brings together microphone-and-headphone packs with four adjustable boom arms for a cleaner shared recording space.",
    features: ["Four podcast mic packs","Headphones included","Four adjustable boom arms"],
    affiliateUrl: "https://focuscamera.pxi6.net/X4Eoj5",
    source: "brand-page",
    pagePath: "/affiliate-services/focus-camera",
  },
  {
    id: "focus-dell-ultrasharp-27-inch-4k-uhd-monitor",
    merchant: "Focus Camera",
    title: "Dell UltraSharp 27-inch 4K UHD Monitor",
    category: "Computers & displays",
    description: "A sharp 27-inch 4K display for detailed creative work, productivity, media, and multi-device desk setups in a clean black-and-silver design.",
    features: ["27-inch 4K UHD display","DisplayPort, USB, and HDMI connectivity","Productivity-focused UltraSharp design"],
    affiliateUrl: "https://focuscamera.pxi6.net/xJoXKk",
    source: "brand-page",
    pagePath: "/affiliate-services/focus-camera",
  },
  {
    id: "focus-dji-flip-fly-more-combo-camera-drone",
    merchant: "Focus Camera",
    title: "DJI Flip Fly More Combo Camera Drone",
    category: "Camera & drone technology",
    description: "A complete compact camera-drone package with the DJI RC 2 controller, extra batteries, charging hub, protective components, and a carrying bag for travel-ready aerial content creation.",
    features: ["DJI RC 2 controller","Extra batteries and charging hub","Carrying bag and Fly More accessories"],
    affiliateUrl: "https://focuscamera.pxi6.net/k4AQKM",
    source: "brand-page",
    pagePath: "/affiliate-services/focus-camera",
  },
  {
    id: "focus-outdoor-survival-bracelet-lifestyle-gear",
    merchant: "Focus Camera",
    title: "Outdoor Survival Bracelet & Lifestyle Gear",
    category: "Explore the main store",
    description: "Explore Focus Camera & Lifestyle for practical outdoor accessories such as this multi-function paracord bracelet, along with cameras, electronics, travel gear, and other current store selections.",
    features: ["Multi-function outdoor accessory","Paracord bracelet design","Links to the full Focus Camera catalog"],
    affiliateUrl: "https://focuscamera.pxi6.net/c/7587435/642856/10228",
    source: "brand-page",
    pagePath: "/affiliate-services/focus-camera",
  },
  {
    id: "focus-beats-solo-4-bluetooth-on-ear-headphones-refurbished",
    merchant: "Focus Camera",
    title: "Beats Solo 4 Bluetooth On-Ear Headphones (Refurbished)",
    category: "Wireless audio",
    description: "Refurbished matte-black Beats Solo 4 on-ear headphones for wireless everyday listening, travel, calls, and compact personal audio.",
    features: ["Bluetooth wireless listening","Built-in digital-to-analog converter","Refurbished matte-black finish"],
    affiliateUrl: "https://focuscamera.pxi6.net/0GzXqY",
    source: "brand-page",
    pagePath: "/affiliate-services/focus-camera",
  },
  {
    id: "focus-apple-11-inch-ipad-with-a16-chip-128gb-wi-fi",
    merchant: "Focus Camera",
    title: "Apple 11-inch iPad with A16 Chip, 128GB Wi-Fi",
    category: "Tablets & mobile technology",
    description: "A silver 11-inch Wi-Fi iPad pairing Apple&apos;s A16 chip with 128GB of storage for browsing, streaming, creative work, communication, and everyday mobile productivity.",
    features: ["11-inch display","Apple A16 chip","128GB Wi-Fi configuration"],
    affiliateUrl: "https://focuscamera.pxi6.net/OYEoqK",
    source: "brand-page",
    pagePath: "/affiliate-services/focus-camera",
  },
  {
    id: "focus-alesis-nitro-ultimate-9-piece-professional-electronic-drum-k",
    merchant: "Focus Camera",
    title: "Alesis Nitro Ultimate 9-Piece Professional Electronic Drum Kit",
    category: "Electronic instruments",
    description: "A nine-piece electronic drum system with a complete rack-mounted pad layout, cymbal pads, drum module, Bluetooth support, and kick-pedal setup for practice, recording, and performance.",
    features: ["Nine-piece electronic drum configuration","Bluetooth-equipped drum module","Rack, cymbal pads, and kick-pedal system"],
    affiliateUrl: "https://focuscamera.pxi6.net/xJoXxR",
    source: "brand-page",
    pagePath: "/affiliate-services/focus-camera",
  },
  {
    id: "focus-outin-fino-portable-electric-coffee-grinder",
    merchant: "Focus Camera",
    title: "OutIn Fino Portable Electric Coffee Grinder",
    category: "Coffee & travel accessories",
    description: "A compact Sandstone White electric coffee grinder built for home or travel, with adjustable settings for dialing in grounds for different brewing methods.",
    features: ["28 grind-size settings","Portable electric design","Cleaning brush and accessories shown"],
    affiliateUrl: "https://focuscamera.pxi6.net/c/7587435/3759881/10228?prodsku=50543834202407&u=https%3A%2F%2Flifestylebyfocus.com%2Fproducts%2Foutin-fino-gr-sw-coffee-espresso-tea-coffee-accessories-tools&intsrc=APIG_30377",
    source: "brand-page",
    pagePath: "/affiliate-services/focus-camera",
  },
  {
    id: "focus-r-de-nt1-signature-series-studio-condenser-microphone-in-pin",
    merchant: "Focus Camera",
    title: "RØDE NT1 Signature Series Studio Condenser Microphone in Pink",
    category: "Studio microphones",
    description: "A pink RØDE NT1 Signature Series studio condenser microphone presented with a shock mount and pop filter for polished vocal, podcast, voice-over, and instrument recording.",
    features: ["Studio condenser microphone","Shock mount included","Pop filter included"],
    affiliateUrl: "https://focuscamera.pxi6.net/VOdRrM",
    source: "brand-page",
    pagePath: "/affiliate-services/focus-camera",
  },
  {
    id: "focus-r-de-nt1-5th-generation-condenser-microphone-in-silver",
    merchant: "Focus Camera",
    title: "RØDE NT1 5th Generation Condenser Microphone in Silver",
    category: "Studio microphones",
    description: "A silver RØDE NT1 5th Generation condenser microphone package with the SM6 shock mount and pop filter for studio vocals, podcasting, voice-over work, and instruments.",
    features: ["5th Generation NT1 microphone","SM6 shock mount","Pop filter included"],
    affiliateUrl: "https://focuscamera.pxi6.net/X4EoPb",
    source: "brand-page",
    pagePath: "/affiliate-services/focus-camera",
  },
  {
    id: "focus-vaonis-vespera-pro-2-smart-telescope",
    merchant: "Focus Camera",
    title: "Vaonis Vespera Pro 2 Smart Telescope",
    category: "Astronomy & astrophotography",
    description: "A compact 12.5MP smart telescope system for guided sky observation and astrophotography, paired with a lightweight tripod for a portable observing setup.",
    features: ["12.5MP imaging system","Smart astrophotography workflow","Portable tripod-mounted design"],
    affiliateUrl: "https://focuscamera.pxi6.net/OYEoXr",
    source: "brand-page",
    pagePath: "/affiliate-services/focus-camera",
  },
  {
    id: "focus-elinchrom-d-lite-rx-4-4-softbox-to-go-kit",
    merchant: "Focus Camera",
    title: "Elinchrom D-Lite RX 4/4 Softbox To Go Kit",
    category: "Studio lighting",
    description: "A portable two-light studio kit with Elinchrom D-Lite RX 4 heads, softboxes, stands, and carrying cases for portraits, products, and location photography.",
    features: ["Two-light studio setup","Softboxes and stands included","Travel cases for location work"],
    affiliateUrl: "https://focuscamera.pxi6.net/R0EYzR",
    source: "brand-page",
    pagePath: "/affiliate-services/focus-camera",
  },
  {
    id: "aquacurve-armrest-loungers-side-tables",
    merchant: "AquaCurve",
    title: "Armrest Loungers & Side Tables",
    category: "Poolside Furniture & Outdoor Living",
    description: "Create a comfortable shallow-water setup with supportive armrests, cup-holder convenience, and a matching table for poolside essentials.",
    features: ["Featured on the WASCIK AquaCurve page","In-pool and sun-shelf furniture"],
    affiliateUrl: "https://aquacurve.sjv.io/c/7587435/3859681/51362?trafsrc=impact",
    source: "brand-page",
    pagePath: "/affiliate-services/aquacurve",
  },
  {
    id: "aquacurve-folding-in-pool-loungers",
    merchant: "AquaCurve",
    title: "Folding In-Pool Loungers",
    category: "Poolside Furniture & Outdoor Living",
    description: "Space-conscious folding loungers bring full-body support to tanning ledges and can fold flatter for storage between pool days.",
    features: ["Featured on the WASCIK AquaCurve page","In-pool and sun-shelf furniture"],
    affiliateUrl: "https://aquacurve.sjv.io/c/7587435/3859681/51362?trafsrc=impact",
    source: "brand-page",
    pagePath: "/affiliate-services/aquacurve",
  },
  {
    id: "aquacurve-teak-look-lounger-sets",
    merchant: "AquaCurve",
    title: "Teak-Look Lounger Sets",
    category: "Poolside Furniture & Outdoor Living",
    description: "Warm wood-look finishes and matching tables add a resort-inspired feel to shallow-water lounging areas and backyard pools.",
    features: ["Featured on the WASCIK AquaCurve page","In-pool and sun-shelf furniture"],
    affiliateUrl: "https://aquacurve.sjv.io/c/7587435/3859681/51362?trafsrc=impact",
    source: "brand-page",
    pagePath: "/affiliate-services/aquacurve",
  },
  {
    id: "aquacurve-colorful-sun-shelf-seating",
    merchant: "AquaCurve",
    title: "Colorful Sun-Shelf Seating",
    category: "Poolside Furniture & Outdoor Living",
    description: "Bright sun-shelf chairs offer a relaxed way to stretch out, socialize, and coordinate furniture with your outdoor space.",
    features: ["Featured on the WASCIK AquaCurve page","In-pool and sun-shelf furniture"],
    affiliateUrl: "https://aquacurve.sjv.io/c/7587435/3859681/51362?trafsrc=impact",
    source: "brand-page",
    pagePath: "/affiliate-services/aquacurve",
  },
];

export const unifiedAffiliateCatalog: UnifiedAffiliateItem[] = [
  ...centralCatalog,
  ...brandPageCatalog,
];
