import { affiliateProducts } from "../../app/affiliate-services/products";

export type UnifiedAffiliateItem = {
  id: string;
  merchant: string;
  title: string;
  category: string;
  description: string;
  features: string[];
  affiliateUrl: string;
  source: "central-catalog" | "brand-page";
  pagePath?: string;
};

const centralCatalog: UnifiedAffiliateItem[] = affiliateProducts.map((product) => ({
  id: `central-${product.id}`,
  merchant: product.merchant,
  title: product.title,
  category: product.category,
  description: product.description,
  features: product.features,
  affiliateUrl: product.affiliateUrl,
  source: "central-catalog",
}));

const brandPageCatalog: UnifiedAffiliateItem[] = [
  {
    id: "eurooptic-garmin-quatix-8-pro",
    merchant: "EuroOptic",
    title: "Garmin Quatix 8 Pro",
    category: "Smartwatches & Outdoor Tech",
    description: "Featured Garmin smartwatch offered through the WASCIK EuroOptic partner page, with current price, availability, specifications, shipping, and returns confirmed at the merchant listing.",
    features: ["Garmin smartwatch", "Outdoor and specialty gear", "Featured EuroOptic product"],
    affiliateUrl: "https://eurooptic.sjv.io/WOEqjX",
    source: "brand-page",
    pagePath: "/affiliate-services/eurooptic",
  },
  {
    id: "eurooptic-store",
    merchant: "EuroOptic",
    title: "EuroOptic Specialty Gear Store",
    category: "Optics, Outdoor Gear & Watches",
    description: "Browse EuroOptic's current optics, outdoor equipment, watches, and specialty gear catalog through WASCIK's tracked store link.",
    features: ["Optics", "Outdoor equipment", "Watches", "Specialty gear"],
    affiliateUrl: "https://eurooptic.sjv.io/c/7587435/2973190/35464",
    source: "brand-page",
    pagePath: "/affiliate-services/eurooptic",
  },
  {
    id: "focus-garmin-dezlcam-otr725",
    merchant: "Focus Camera",
    title: "Garmin dezlCam OTR725",
    category: "GPS Navigation & Dash Cameras",
    description: "A seven-inch GPS truck navigator with a built-in dash camera for professional drivers and life on the road.",
    features: ["7-inch touchscreen", "Built-in dash camera", "Truck navigation"],
    affiliateUrl: "https://focuscamera.pxi6.net/3kzXRX",
    source: "brand-page",
    pagePath: "/affiliate-services/focus-camera",
  },
  {
    id: "focus-camera-store",
    merchant: "Focus Camera",
    title: "Focus Camera Main Store",
    category: "Cameras, Navigation, Electronics & Lifestyle",
    description: "Browse current camera, navigation, electronics, and lifestyle products through WASCIK's tracked Focus Camera store link.",
    features: ["Cameras", "Navigation", "Electronics", "Lifestyle products"],
    affiliateUrl: "https://focuscamera.pxi6.net/c/7587435/642856/10228",
    source: "brand-page",
    pagePath: "/affiliate-services/focus-camera",
  },
  {
    id: "aquacurve-store",
    merchant: "AquaCurve",
    title: "AquaCurve Poolside & Outdoor Living Catalog",
    category: "Poolside Furniture & Outdoor Living",
    description: "Browse AquaCurve's current poolside and outdoor-living catalog through the WASCIK affiliate store link.",
    features: ["Poolside furniture", "Outdoor living", "Patio and leisure products"],
    affiliateUrl: "https://aquacurve.sjv.io/c/7587435/3859681/51362?trafsrc=impact",
    source: "brand-page",
    pagePath: "/affiliate-services/aquacurve",
  },
  {
    id: "gearup-mobile",
    merchant: "GearUP",
    title: "GearUP for Mobile",
    category: "Gaming Network Optimization",
    description: "A mobile game connection-optimization service for Android and iOS players dealing with unstable latency, lag spikes, or high ping.",
    features: ["Android and iOS", "One-tap boosting", "Worldwide game servers", "Connection optimization"],
    affiliateUrl: "https://gearupapp.pxf.io/c/7587435/3911079/53368",
    source: "brand-page",
    pagePath: "/affiliate-services/gearup",
  },
  {
    id: "arccaptain-store",
    merchant: "ArcCaptain",
    title: "ArcCaptain Welding Equipment",
    category: "Welding Equipment & Accessories",
    description: "Browse ArcCaptain MIG, TIG, stick, and plasma equipment, along with welding helmets and accessories through WASCIK's approved affiliate link.",
    features: ["MIG welding", "TIG welding", "Stick and plasma equipment", "Welding helmets and accessories"],
    affiliateUrl: "https://arccaptain.pxf.io/c/7587435/3898395/52929",
    source: "brand-page",
    pagePath: "/affiliate-services#arccaptain",
  },
  {
    id: "ticketnetwork-store",
    merchant: "TicketNetwork",
    title: "TicketNetwork Concerts & Event Tickets",
    category: "Concerts, Events & Tickets",
    description: "Search current TicketNetwork listings for concerts and events through WASCIK's ticket affiliate page.",
    features: ["Concert tickets", "Live events", "Current seat listings", "Ticket resale marketplace"],
    affiliateUrl: "https://goto.ticketnetwork.com/c/7587435/120057/2322",
    source: "brand-page",
    pagePath: "/affiliate-services/ticketnetwork",
  },
  {
    id: "ticketnetwork-chris-stapleton",
    merchant: "TicketNetwork",
    title: "Chris Stapleton — All-American Road Show",
    category: "Country Concert",
    description: "Chris Stapleton with Zach Top and Allen Stone, Friday, August 14, 2026 at 7:30 PM, Fenway Park in Boston, Massachusetts.",
    features: ["Featured on WASCIK TicketNetwork page", "Concert ticket search", "Country Concert"],
    affiliateUrl: "https://goto.ticketnetwork.com/c/7587435/120057/2322",
    source: "brand-page",
    pagePath: "/affiliate-services/ticketnetwork",
  },
  {
    id: "ticketnetwork-kane-brown",
    merchant: "TicketNetwork",
    title: "Kane Brown — OC Smoke Show",
    category: "Country Concert",
    description: "Kane Brown with Dustin Lynch and LoCash, Saturday, August 15, 2026 at 1:00 PM, Rancho Mission Viejo Riding Park in San Juan Capistrano, California.",
    features: ["Featured on WASCIK TicketNetwork page", "Concert ticket search", "Country Concert"],
    affiliateUrl: "https://goto.ticketnetwork.com/c/7587435/120057/2322",
    source: "brand-page",
    pagePath: "/affiliate-services/ticketnetwork",
  },
  {
    id: "ticketnetwork-guns-n-roses",
    merchant: "TicketNetwork",
    title: "Guns N’ Roses with Public Enemy",
    category: "Rock Concert",
    description: "Guns N’ Roses with Public Enemy, Sunday, August 16, 2026 at 6:25 PM, Busch Stadium in St. Louis, Missouri.",
    features: ["Featured on WASCIK TicketNetwork page", "Concert ticket search", "Rock Concert"],
    affiliateUrl: "https://goto.ticketnetwork.com/c/7587435/120057/2322",
    source: "brand-page",
    pagePath: "/affiliate-services/ticketnetwork",
  },
  {
    id: "ticketnetwork-pitbull",
    merchant: "TicketNetwork",
    title: "Pitbull with Lil Jon",
    category: "Pop & Hip-Hop Concert",
    description: "Pitbull with Lil Jon, Wednesday, August 19, 2026 at 8:00 PM, Jiffy Lube Live in Bristow, Virginia.",
    features: ["Featured on WASCIK TicketNetwork page", "Concert ticket search", "Pop & Hip-Hop Concert"],
    affiliateUrl: "https://goto.ticketnetwork.com/c/7587435/120057/2322",
    source: "brand-page",
    pagePath: "/affiliate-services/ticketnetwork",
  },
  {
    id: "ticketnetwork-garth-brooks-aug-20",
    merchant: "TicketNetwork",
    title: "Garth Brooks Live — August 20",
    category: "Country Concert",
    description: "Garth Brooks live, Thursday, August 20, 2026 at 7:30 PM, Gainbridge Fieldhouse in Indianapolis, Indiana.",
    features: ["Featured on WASCIK TicketNetwork page", "Concert ticket search", "Country Concert"],
    affiliateUrl: "https://goto.ticketnetwork.com/c/7587435/120057/2322",
    source: "brand-page",
    pagePath: "/affiliate-services/ticketnetwork",
  },
  {
    id: "ticketnetwork-garth-brooks-aug-21",
    merchant: "TicketNetwork",
    title: "Garth Brooks Live — August 21",
    category: "Country Concert",
    description: "Garth Brooks live, Friday, August 21, 2026 at 8:00 PM, Gainbridge Fieldhouse in Indianapolis, Indiana.",
    features: ["Featured on WASCIK TicketNetwork page", "Concert ticket search", "Country Concert"],
    affiliateUrl: "https://goto.ticketnetwork.com/c/7587435/120057/2322",
    source: "brand-page",
    pagePath: "/affiliate-services/ticketnetwork",
  },
  {
    id: "ticketnetwork-garth-brooks-aug-22",
    merchant: "TicketNetwork",
    title: "Garth Brooks Live — August 22",
    category: "Country Concert",
    description: "Garth Brooks live, Saturday, August 22, 2026 at 8:00 PM, Gainbridge Fieldhouse in Indianapolis, Indiana.",
    features: ["Featured on WASCIK TicketNetwork page", "Concert ticket search", "Country Concert"],
    affiliateUrl: "https://goto.ticketnetwork.com/c/7587435/120057/2322",
    source: "brand-page",
    pagePath: "/affiliate-services/ticketnetwork",
  },
  {
    id: "ticketnetwork-garth-brooks-aug-23",
    merchant: "TicketNetwork",
    title: "Garth Brooks Live — August 23",
    category: "Country Concert",
    description: "Garth Brooks live, Sunday, August 23, 2026 at 2:00 PM, Gainbridge Fieldhouse in Indianapolis, Indiana.",
    features: ["Featured on WASCIK TicketNetwork page", "Concert ticket search", "Country Concert"],
    affiliateUrl: "https://goto.ticketnetwork.com/c/7587435/120057/2322",
    source: "brand-page",
    pagePath: "/affiliate-services/ticketnetwork",
  },
  {
    id: "ticketnetwork-weezer",
    merchant: "TicketNetwork",
    title: "Weezer with The Shins & Silversun Pickups",
    category: "Alternative Rock Concert",
    description: "Weezer with The Shins and Silversun Pickups, Tuesday, October 6, 2026 at 7:00 PM, Nationwide Arena in Columbus, Ohio.",
    features: ["Featured on WASCIK TicketNetwork page", "Concert ticket search", "Alternative Rock Concert"],
    affiliateUrl: "https://goto.ticketnetwork.com/c/7587435/120057/2322",
    source: "brand-page",
    pagePath: "/affiliate-services/ticketnetwork",
  },
  {
    id: "ticketnetwork-journey",
    merchant: "TicketNetwork",
    title: "Journey Live in Concert",
    category: "Classic Rock Concert",
    description: "Journey live, Thursday, October 8, 2026 at 7:30 PM, BOK Center in Tulsa, Oklahoma.",
    features: ["Featured on WASCIK TicketNetwork page", "Concert ticket search", "Classic Rock Concert"],
    affiliateUrl: "https://goto.ticketnetwork.com/c/7587435/120057/2322",
    source: "brand-page",
    pagePath: "/affiliate-services/ticketnetwork",
  },
];

export const unifiedAffiliateCatalog: UnifiedAffiliateItem[] = [
  ...centralCatalog,
  ...brandPageCatalog,
];
