create table if not exists public.wascik_leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  status text not null default 'new' check (status in ('new','contacted','in_progress','closed')),
  session_id text,
  source_page text not null default '/',
  name text,
  email text,
  phone text,
  business text not null,
  project_type text not null,
  budget text,
  timeline text,
  summary text not null,
  contacted_at timestamptz,
  closed_at timestamptz
);

alter table public.wascik_leads enable row level security;

-- No anon/authenticated browser policies are intentionally created here.
-- Production reads/writes should go through trusted server-side code.
-- Keep the Supabase service-role key only in server environment variables.

create index if not exists wascik_leads_status_idx on public.wascik_leads(status);
create index if not exists wascik_leads_created_at_idx on public.wascik_leads(created_at desc);
create index if not exists wascik_leads_source_page_idx on public.wascik_leads(source_page);
